FROM node:10 AS BUILD_IMAGE

RUN curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | bash -s -- -b /usr/local/bin

WORKDIR /app

COPY . /app

#RUN npm install
RUN npm i --registry=https://registry.npm.taobao.org

# remove development dependencies
RUN npm prune --production

# run node prune
RUN /usr/local/bin/node-prune

# ========================================================================================================
FROM node:10-alpine

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app/

# copy from build image
COPY --from=BUILD_IMAGE /app /usr/src/app/

RUN npm run build

EXPOSE 7001
CMD npm run start
