name: Deploy::TEST

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - 'docs/**'
      - 'scripts/**'
      - '*.md'
      - '*.editorconfig'
      - '*.gitignore'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Read Env
        id: props
        uses: hocgin/action-json-file-to-env@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          debug: true
