name: Deploy::TEST

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - 'docs/**'
      - 'scripts/**'
      - '*.md'
      - '*.editorconfig'
      - '*.gitignore'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Read Env
        id: props
        uses: hocgin/action-json-file-to-env@v0.0.4
        with:
          debug: true
